---
stages:
  - verify
  - test-default
  - test-with-extra-sidecars

image:
  name: registry.ednz.fr/forge/ansible-runner

variables:
  ANSIBLE_HOST_KEY_CHECKING: 'false'
  ANSIBLE_FORCE_COLOR: 'true'
  ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3
  DOCKER_AUTH_CONFIG: $CI_DOCKER_AUTH_CONFIG

.stage-test-default:
  stage: test-default

.stage-test-with-extra-sidecars:
  stage: test-with-extra-sidecars

.variables-ubuntu-2004:
  variables:
    MOLECULE_TEST_OS: "ubuntu2004"

.variables-ubuntu-2204:
  variables:
    MOLECULE_TEST_OS: "ubuntu2204"

.variables-debian-11:
  variables:
    MOLECULE_TEST_OS: "debian11"

.script-molecule-test-default:
  script:
    - molecule test

.script-molecule-test-with-extra-sidecars:
  script:
    - molecule test -s with_extra_sidecars

ansible-verify:
  stage: verify
  script:
    - yamllint . -c .yamllint
    - ansible-lint

ansible-test-ubuntu-2004-default:
  extends:
    - .stage-test-default
    - .variables-ubuntu-2004
    - .script-molecule-test-default

ansible-test-ubuntu-2204-default:
  extends:
    - .stage-test-default
    - .variables-ubuntu-2204
    - .script-molecule-test-default

ansible-test-debian-11-default:
  extends:
    - .stage-test-default
    - .variables-debian-11
    - .script-molecule-test-default

ansible-test-ubuntu-2004-with-extra-sidecars:
  extends:
    - .stage-test-with-extra-sidecars
    - .variables-ubuntu-2004
    - .script-molecule-test-with-extra-sidecars

ansible-test-ubuntu-2204-with-extra-sidecars:
  extends:
    - .stage-test-with-extra-sidecars
    - .variables-ubuntu-2204
    - .script-molecule-test-with-extra-sidecars

ansible-test-debian-11-with-extra-sidecars:
  extends:
    - .stage-test-with-extra-sidecars
    - .variables-debian-11
    - .script-molecule-test-with-extra-sidecars
