---
# handlers file for deploy_adguard
- name: "Reload systemd file"
  ansible.builtin.systemd:
    daemon_reload: true
  listen: "systemctl-daemon-reload"

- name: "Enable adguard service"
  ansible.builtin.service:
    name: adguard
    enabled: true
  listen: "systemctl-enable-adguard"

- name: "Start adguard service"
  ansible.builtin.service:
    name: adguard
    state: restarted
  listen: "systemctl-restart-adguard"
  throttle: 1
  when: deploy_adguard_start_service

- name: "Enable adguard-connect-proxy service"
  ansible.builtin.service:
    name: adguard-connect-proxy
    enabled: true
    state: restarted
  listen: "systemctl-enable-restart-adguard-connect-proxy"
